# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "azurerm" {
    container_name       = "terraform"
    key                  = "./terraform.tfstate"
    resource_group_name  = "susilnemterraformstate-rg"
    storage_account_name = "susilnemtfstate"
  }
}
